### ISSUE TITLE
Set and document exit codes

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-aem-rde#18]
Similar to https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/215 all commands should indicate failures also via the exit code in order to ease using the commands in automation scripts. Currently failures just lead to log messages (e.g. in https://github.com/adobe/aio-cli-plugin-aem-rde/blob/e60e09ec24d51ad1db11e3a44c8f32744ed8cedc/src/commands/aem/rde/install.js#L189-L200).)

It would be good to reuse the exit code categories defined in https://github.com/adobe/aio-cli-plugin-cloudmanager#exit-codes.

**Comment by RemoLiechti** [comment]
fixed by https://github.com/adobe/aio-cli-plugin-aem-rde/pull/53
