### ISSUE TITLE
Evaluate global flags "programId" and "environmentId"

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-aem-rde#22]
Although in https://github.com/adobe/aio-cli-plugin-aem-rde/blob/e60e09ec24d51ad1db11e3a44c8f32744ed8cedc/src/lib/base-command.js#L160 the CLI arguments `programId` and `environmentId` are stored as global flags, those are not considered in https://github.com/adobe/aio-cli-plugin-aem-rde/blob/e60e09ec24d51ad1db11e3a44c8f32744ed8cedc/src/lib/base-command.js#L93. Please only fallback to the Config values in case no CLI flags are given.

**Comment by RemoLiechti** [comment]
This is on our schedule currently.

**Comment by RemoLiechti** [comment]
tagged: SKYOPS-76823

**Comment by RemoLiechti** [comment]
fixed with #74
