### ISSUE TITLE
Conflicting requirements in package.json

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-aem-rde#25]
In the package.json I see the following requirements (https://github.com/adobe/aio-cli-plugin-aem-rde/blob/e60e09ec24d51ad1db11e3a44c8f32744ed8cedc/package.json#L6):

```
"engines": {
    "npm": "^8.0.0",
    "node": "^16.13 || >=18"
  },
```

This leads to warning during installation, as newer versions of node (e.g. the latest LTS) ship with NPM 9.x. (https://nodejs.org/en/download/releases/):

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@adobe/aio-cli-plugin-aem-rde@0.0.1-alpha.11',
npm WARN EBADENGINE   required: { npm: '^8.0.0', node: '^16.13 || >=18' },
npm WARN EBADENGINE   current: { node: 'v19.6.0', npm: '9.4.0' }
npm WARN EBADENGINE }
```

I think that adding a requirement on the node version is sufficient.

**Comment by RemoLiechti** [comment]
this was fixed with #65
