### ISSUE TITLE
Pull Request action fails to check out code if branch is on a fork

### ISSUE THREAD

**Issue by bosschaert** [adobe/aio-cli-plugin-aem-rde#29]
If you look at #27, you'll see that the git checkout fails, with the following.

```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/SKYOPS-46671*:refs/remotes/origin/SKYOPS-46671* +refs/tags/SKYOPS-46671*:refs/tags/SKYOPS-46671*
  The process '/usr/bin/git' failed with exit code 1
```

That change is on a branch on a fork

#28 is the same change but then on a 'local' branch where it works.

So the PR action doesn't work if the branch is on a fork.

**Comment by RemoLiechti** [comment]
not an issue for now
