### ISSUE TITLE
Allow the status to be exported as json

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aio-cli-plugin-aem-rde#32]
We would like to use the RDE env in a CI / CD environment, where we need to know if the environment is available before installing a next package. 

The aem:rde:status is a textual description, it is non-parseable for an automated system. 

Feature request:
- Add a json output for the status command

**Comment by RemoLiechti** [comment]
@royteeuwen see #77 that adds json output for all commands in the next release.
