### ISSUE TITLE
Set error exit code (!= 0) for "Error: 403 - Forbidden"

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-aem-rde#43]
When I call e.g. `aem:rde:reset` I get back the output `Error: 403 - Forbidden` however the CLI exits with the success exit code (0). In case of errors always indicate that with an exit code != 0 to ease automatically evaluating the outcome. This is related to #18 .

**Comment by RemoLiechti** [comment]
fixed by https://github.com/adobe/aio-cli-plugin-aem-rde/pull/53
