### ISSUE TITLE
Document how to enable DEBUG log

### ISSUE THREAD

**Issue by kwin** [adobe/aio-cli-plugin-aem-rde#44]
I would like to see the log output e.g. from https://github.com/adobe/aio-lib-ims/blob/d45606dec20577ba953b3968aa0ae1e518ab3855/src/token-helper.js#L111C1-L111C1.

I tried setting environment variable AIO_LOG_LEVEL=debug (as described in https://github.com/adobe/aio-lib-core-logging#configuration) but although some debug messages are now logged, the one listed above is not.

Please extend the readme on how to enable debug level logging for all modules!

**Comment by RemoLiechti** [comment]
Thanks for pointing this out, we will add a step by step description how to enable the debug logs.

**Comment by RemoLiechti** [comment]
tagged SKYOPS-73008

**Comment by jsedding** [comment]
This should be (untested) `DEBUG=AIO` or `DEBUG=*` for all debug logs.

**Comment by RemoLiechti** [comment]
fixed with https://github.com/adobe/aio-lib-core-logging/pull/55

**Comment by RemoLiechti** [comment]
see official documentation 
https://github.com/adobe/aio-lib-core-logging?tab=readme-ov-file#enabling-debug-level-logging
