### ISSUE TITLE
Allow the reset command to be executed in the background

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aio-cli-plugin-aem-rde#45]
### Expected Behaviour
Triggering the `aio aem:rde reset` command in a CI / CD pipeline is commonly the last command to be executed. The build status could already be set to succeeded or failed independently of the reset of the environment. It should be possible to trigger a reset without waiting for the finishing of that reset

### Actual Behaviour
Currently the reset command is always blocking

**Comment by RemoLiechti** [comment]
This is on our schedule currently.
